---
title: "TidyTuesday_achievements"
author: "Sil Aarts"
date: "6/8/2020"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r echo=F, warnings=F, message=F}

#Tidytuesday - Achievements

#Load libraries
library(tidyverse)
library(RColorBrewer)
library(cowplot)
library(ggtext)
library(ggridges)
library(extrafont)
library(wesanderson)



#Load data
firsts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/firsts.csv')

```

```{r echo=F, warnings=F, message=F}
#Count (not used in this plot)
data <- firsts %>%
  group_by(category, year) %>%
  dplyr::mutate(category_total = n()) 
```

```{r echo=F, warnings=F, message=F}
theme_plot <-  theme_void()+
    theme(
    text = element_text(family="Verdana"),
    plot.margin = unit(c(1,2,0.5,1), "cm"),
    legend.text = element_text(size=25, family="Verdana"),
    legend.title = element_blank(),
    legend.background = element_rect(fill="transparent",size= 1.5, linetype="solid", colour ="white"),
    legend.position = c(0.25, 0.05),
    plot.subtitle = element_markdown(color="gray33", size=35, hjust=0.5, margin=margin(0, 0, 0, 0), family="Verdana"), #t,r,b,l
    plot.title = element_markdown(color="white", size=50, face="bold", hjust=0.5, margin = margin(0, 0, 50, 0)),
    plot.caption = element_text(color="white", size=18, hjust=0.5, margin=margin(50, 0, 0, 0)),
    axis.text.y = element_text(size=30, colour="white", face="bold", margin = margin(t = 0, r = 0, b = 0, l = 30)),
    axis.ticks.y = element_line(size=3, colour="white"),
    axis.line.y = element_line(color="black", size = 0.5),
    panel.background = element_rect(fill = "grey68", color="grey68"),
    plot.background = element_rect(fill = "grey68", color="grey68"),
    strip.background = element_rect(fill = NA, color = NA))

```

```{r echo=F, warnings=F, message=F}
#Make some colours
colors <- wes_palette("Darjeeling2", 8, type="continuous")
```

```{r fig.width = 12, fig.height = 30}
#GGplot
p <- ggplot(data, aes(x=year, y=category))+
  geom_point(aes(colour=category), size = 5, alpha=0.7)+
  scale_x_continuous(breaks=c(1750,1800,1850,1900,1950,2000), position="top")+
  scale_colour_manual(values=colors)+
  coord_flip()+
  labs(caption= "Source: Wikipedia | David Blackwell & Petition for David Blackwell\nPlot by @sil_aarts",
       x="", 
       y="",
       subtitle = "Achievements from 1738 to 2019",
       title="African-American <br> Achievements")+
  theme_plot
  

#Run it!
p
```

